### ISSUE TITLE
Backup etcd

### ISSUE THREAD

**Issue by corvus-ch** [projectsyn/component-cluster-backup#1]
The [OpenShift 4 documentation](https://docs.openshift.com/container-platform/4.5/backup_and_restore/backing-up-etcd.html) explains how to backup etcd of a cluster.

* Make this procedure work within a container
* Make this component to configure K8up objects for backing up the etcd

**Comment by corvus-ch** [comment]
The OpenShift documentation suggests to use `oc debug node/master…`, then `chroot /host`. From there a script can be executed that creates a backup of the etcd along with the static pods.

Based on the debug pod, we can create a k8up pre backup pod that does the above and writes the result to STDOUT.

```bash
#!/bin/bash

# Prepare a clean working directory
outdir='/host/home/core/assets/backup/'
rm -rf "${outdir}"
mkdir -p "${outdir}"
cd "${outdir}"

# Create backup data
# See https://docs.openshift.com/container-platform/4.5/backup_and_restore/backing-up-etcd.html
chroot /host /usr/local/bin/cluster-backup.sh /home/core/assets/backup >&2

# Assert assumptions
# The commands after those assertions will yield unexpected results if assumptions are not met.
if [ "$(ls snapshot*.db | wc -l)" -gt "1" ]; then
  echo 'assumptions unmet: got more than one `snapshot*.db` file' >&2 
  exit 1
fi

if [ "$(ls static_kuberesources_*.tar.gz | wc -l)" -gt "1" ]; then
  echo 'assumptions unmet: got more than one `static_kuberesources_*.tar.gz ` file' >&2
  exit 1
fi

# Bundle backup data in single tar archive
mv snapshot*.db snapshot.db
tar xzf static_kuberesources_*.tar.gz
tar cf output.tar snapshot.db static-pod-resources

# Write backup to STDOUT to be picked up by k8up
<output.tar >&1
```

The pod would then look like this:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: etcd-dump-test
  namespace: syn-cluster-backup
spec:
  containers:
  - command:
      - tail
      - -f
      - /dev/null
    name: etcd-dump
    image: …
    imagePullPolicy: Always
    securityContext:
      privileged: true
      runAsUser: 0
    volumeMounts:
    - mountPath: /host
      name: host
  hostNetwork: true
  hostPID: true
  nodeSelector:
    node-role.kubernetes.io/master: ""
  priority: 0
  tolerations:
  - effect: NoSchedule
    operator: Exists
    key: node-role.kubernetes.io/master
  volumes:
  - hostPath:
      path: /
      type: Directory
    name: host
```

For the NodeSelector to work, the namespace `syn-cluster-backup` needs the annotation `openshift.io/node-selector=""`. This then has the consequence, that each and every workload within that namespace, needs NodeSelector set explicitly.
